[project]
name = "sonwet"
version = "0.1.0"
description = "An all in one solution for accumulating and querying weather and sun data over time."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apscheduler>=3.11.2",
    "requests>=2.34.2",
]
[project.scripts]
sonwet = "sonwet:main"